### ISSUE TITLE
datashader import issue in 18_points

### ISSUE THREAD

**Issue by weikang9009** [sjsrey/pysalnarsc17#9]
![image](https://user-images.githubusercontent.com/7359284/32149428-89ce336c-bcc1-11e7-927e-09146daafc44.png)

The [reason](https://github.com/bokeh/datashader/issues/208) is that conda-forge chanel does not give the most updated version of datashader. It is version 0.3.0 on  conda-forge channel.
![image](https://user-images.githubusercontent.com/7359284/32149476-6c34c2f2-bcc2-11e7-87d4-212af1cb5190.png)

Need to add the channel "bokeh" to get the most updated version of datashader (0.6.2) to get it to work.
![image](https://user-images.githubusercontent.com/7359284/32149484-93068546-bcc2-11e7-9715-c116479ad86f.png)

**Comment by sjsrey** [comment]
nice work
